name: irh_editor
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  appflowy_editor: ^3.2.0
  syntax_highlight: ^0.4.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
